### ISSUE TITLE
Validate Datepicker containing only date portion

### ISSUE THREAD

**Issue by Braytiner** [aspnet/jquery-validation-unobtrusive#103]
I use Asp.Net Core MVC (Razor + Jquery Validate + Unobtrusive). I display in a Datepicker only the date portion of a DateTime field through the following code in my ViewModel:

[Required]
[DataType(DataType.Date)]
public DateTime TargetDate { get; set; } = DateTime.Now;
However, in my view, typing the contents of the field with a valid date, I get the error message "Please enter a valid date."

When the data annotation [DataType.Date] is removed and the time share is displayed, the validation works correctly, so it is not a location problem

I have also added the following annotation date to ViewModel, but I did not succeed:

 [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
I'm not sure, but from what I think the problem is in unobtrusive validation that does not seem to behave right with inputs that display only part of the date.

How to solve this problem?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Braytiner.
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by ryanbrandenburg** [comment]
@Braytiner please upload a minimal repro app to GitHub and link it here so that I can be sure I understand the context of your issue.

**Comment by danroth27** [comment]
@dougbu Do we support `[DataType(DataType.Date)]` on a `DateTime`?

**Comment by dougbu** [comment]
FYI the (minimal) `IsValid(...)` code for this attribute is just https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/DataTypeAttribute.cs#L105-L110

**Comment by mkArtakMSFT** [comment]
@Braytiner, please provide a minimalistic repro hosted in GitHub, so we can investigate this further.

**Comment by dougbu** [comment]
@Braytiner FYI the generated HTML when you're using `[DataType(DataType.Date)]` *should* at most enforce the `[Required]` attribute using unobtrusive validation.

I suspect the default `Date` format (`"{0:d}"`) (or `[DisplayFormat(..., DataFormatString = "{0:MM/dd/yyyy}")]`) causes your browser to show a text box instead of a date picker. Then, users enter something invalid for the current culture and a server validation error occurs. But, I won't be sure until we see the repro @mkArtakMSFT requested.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by Braytiner** [comment]
Sorry guys! After two months I encountered the problem: the validation function in methods_pt.js has some errors, so I overwrited this with another function and it worked. So, the error wasn't in unobtrusive validation.

Thanks for your patience after this long time.
