### ISSUE TITLE
Add hooks for various events, and allow configuration

### ISSUE THREAD

**Issue by lonix1** [aspnet/jquery-validation-unobtrusive#104]
This plugin has been a pain to use since the very beginning, since it both conceals the underlying jQuery validate plugin, and doesn't allow you to (easily) override the configuration.

Just look at the number of questions on StackOverflow to get an idea how much of a problem this is.

We've been [using this approach](https://gist.github.com/beccasaurus/957732/a41a90675e9b9bcb8f4fdccce443b51cf858de72) for a long time, to get hooks that we can use for styling, validation events (for forms and for elements), etc.

The plugin's original authors meant well by creating an easy to use plugin for something that is difficult to do - but it's old and nasty now, and needs to be brought up to date.

It's high time this *functionality is available in the library directly*, please consider it!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lonix1.
@danroth27, thoughts?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by lonix1** [comment]
There is plenty of community interest - check StackOverflow. This plugin has one of the most horrible API designs imaginable, and it has been that way for over a decade.

As long as the templates still use jQuery Unobtrusive Validation, it needs to be updated. Working with forms is a incredible pain, just because of this library.

**Comment by shapeh** [comment]
@ionix1 - can you elaborate a bit on what the problems seem to be? We work with this plugin on various sites - and rarely have any problems. 
That could be due to the fact that most of form validation happens on simple forms and does not require too much logic to validate.
