### ISSUE TITLE
Missing dist folder again #1877

### ISSUE THREAD

**Issue by wolfkumpitsch1** [aspnet/jquery-validation-unobtrusive#105]
breaking PROD version
dist folder added to ignore in .gitignore

is this going to be the future default?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @wolfkumpitsch1.
@ryanbrandenburg, what was the motivation for ignoring `dist` folder?

**Comment by Eilon** [comment]
We removed it because the idea was that running `build` (or whatever) will produce it. We don't check in build outputs into the repo, only the "source code."

But I warned this might break something!

Having said that, @wolfkumpitsch1 , can you provide info on what you were doing and how you saw an error?

**Comment by Eilon** [comment]
This was the PR that removed it: https://github.com/aspnet/jquery-validation-unobtrusive/pull/99

**Comment by ryanbrandenburg** [comment]
@wolfkumpitsch1 I think we're asking more like how are you acquiring and using the package. IE, npm, git, nuget etc.

**Comment by wolfkumpitsch1** [comment]
Ah. Sorry.
NPM in VS2017, the setup was created by a 3rd party a few years ago, not my field of strength, sorry.

**Comment by Eilon** [comment]
Hi @wolfkumpitsch1 , Bower is unfortunately no longer supported by us and we recommend using an alternative such as NPM to acquire static assets such as this project.

**Comment by mkArtakMSFT** [comment]
@wolfkumpitsch1, we still don't understand what you're having trouble with. Please provide a repo in GitHub that demonstrates your problem, so we can investigate it.

**Comment by danroth27** [comment]
After chatting with @javiercn it sounds like Bower in particular expects that the repo contains a dist folder with the production files (i.e. minified), so removing this folder from the repo broke Bower scenarios. That said, you may be able to point to an earlier tagged version that still has the dist folder (ex https://github.com/aspnet/jquery-validation-unobtrusive/tree/v3.2.10).

**Comment by danroth27** [comment]
@wolfkumpitsch1 Can you switch to using npm directly instead?

**Comment by Eilon** [comment]
Right, breaking Bower was an explicit decision that was made, so that was deliberate.

**Comment by ryanbrandenburg** [comment]
Sounds like you have this under control then. Closing.
