### ISSUE TITLE
Changing Language of ErrorMessages

### ISSUE THREAD

**Issue by sxndy1** [aspnet/jquery-validation-unobtrusive#113]
Hey guys,

I've set the validation rules via data annotations in my model.

On my local machine (german environment) my error messages are shown in german language. Everything fine. But after deploying to the server the messages on the website are shown in english. But I want them in german language like on my local machine.

My questions are:
1) How can I explicit activate the already **existing** german language for error messages? I want to avoid to define a custom message in the annotations while the correct german language already exists.
2) Or how it is recognized in which language the messages have to be? Maybe I can change a setting on the server where the validation is checking out which language it has to take.

Would be great, if anybody can help me.

**Comment by EdwardGray953** [comment]
Sounds like there is some localisation available on the server/website. You probably need to configure the website to select the correct localisation for each session, which in turn should provide the language-specific error messages (I'm assuming that the pages themselves are designed to display in different languages).

**Comment by sxndy1** [comment]
When displaying all possible server localisation and globalisation variables to the page they're all set to german. But still english error messages.

And no, it's a pretty small web application for intranet, only one language.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
