### ISSUE TITLE
StringLength validation does not account for \r\n

### ISSUE THREAD

**Issue by EdwardGray953** [aspnet/jquery-validation-unobtrusive#118]
When checking stringlength with JS, new lines are normalised to the linefeed (\n) character. When submitted and input, they are typically entered as CRLF (\r\n).

Should the stringlength validation account for the missing CR (\r) character when validating?

As an example, the following string would evaluate to a length of 9 characters:
abcdCRLFefgh

**Comment by RobJohnston** [comment]
There is an upstream issue that address this at  https://github.com/jquery-validation/jquery-validation/issues/2101

In that issue, the explanation of the HTML5 specification gives the reason why browsers do this and a work-around is provided.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
