### ISSUE TITLE
aria-describedby issues - applying & removing

### ISSUE THREAD

**Issue by EdwardGray953** [aspnet/jquery-validation-unobtrusive#119]
aria-describedby attributes are not updated/removed when a field validates correctly
The attribute should be removed when the error ID is the only ID in the list.
The error ID should be removed from the list when there are other IDs in the list.

aria-describedby is also applied whenever an element is validated, regardless of whether the element validates successfully or not. Should only be applied if the element validates unsuccessfully.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
