### ISSUE TITLE
Groups not working

### ISSUE THREAD

**Issue by dbarwikowski** [aspnet/jquery-validation-unobtrusive#123]
I've tried to add group validation for 3 inputs (date splitted on day | month | year)
in jquery.validate there is an option for that
```
$('form').validate({
    groups: {
        date: 'day month year'
    },
    rules: {
        day: {...},
        month: {...},
        year: {...}
    },
    messages: {
        day: {...},
        month: {...},
        year: {...}
    }
})
```

whenever there is invalid value in one of the inputs then one error is displayed.

Is there a possibility to add this to the unobtrusive validation?

`data-val-group="birthDate"`

**Comment by glombek** [comment]
Basic group functionality can be implemented with a custom adapter, like so:

```
$.validator.unobtrusive.adapters.add("group", [], function (options) {
    var uv = $(options.form).data("unobtrusiveValidation");
    uv.options.groups = uv.options.groups || {};

    var current = uv.options.groups[options.message] || "";

    uv.options.groups[options.message] = (current + " " + options.element.id).trim();
});
```

Then add `data-val-group="groupName"` (no spaces allowed) to each element in the group.

This only provides the same functionality as what you described above, no additional grouping logic.

**Comment by mkArtakMSFT** [comment]
Thanks for helping out with this, @glombek 👍
