### ISSUE TITLE
content security policy src : self ,  violation occurs for style added through javascript file

### ISSUE THREAD

**Issue by rameshbsupekar** [aspnet/jquery-validation-unobtrusive#128]
` <span class="text-danger"><div class="validation-summary-valid" data-valmsg-summary="true"><ul><li style="display:none"></li>`

above line is geettig added in page where library is used in this inline style display none is getting added
to fix this seprate css file can be created and class can be assigned to ul where style needs to be given

following error is shown in developer tools
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'  

If there are any other inline styles getting added dynamically can be added in seprate css file and linked

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
