### ISSUE TITLE
jquery-validation-unobtrusive and jQuery.validate  dont play well together

### ISSUE THREAD

**Issue by Byron2016** [aspnet/jquery-validation-unobtrusive#130]
Versions:
- jquery-validation-unobtrusive: v3.2.11
- jquery.validate(): v1.19.2

Problem:
My validations work well with jquery.validate() or with  jquery-validation-unobtrusive; but if with two working together they doesn´t work anymore.

How can I solve the problem? Maybe someone has the solution?

**Comment by mkArtakMSFT** [comment]
Closing as the versions have been updated since then.
