### ISSUE TITLE
Very very poor performance invoking 'unobtrusive.parse' on large forms

### ISSUE THREAD

**Issue by onionhammer** [aspnet/jquery-validation-unobtrusive#14]
As an example; a form with something on the order of 800 fields, and it takes about 8 seconds to parse  on Chrome, quad core i7 (2.8ghz) with 16 gb of ram. That's 100 fields per second, which is pretty slow.

**Comment by ryanbrandenburg** [comment]
@onionhammer I'm not able to reproduce any slowness in JS or unobtrusive.parse, but I DID find a perf problem with lots of @Html.EditorFor's on a page when the model is null and the debugger is attached. Could you check your browsers network tab for me? If your request is spending a lot of time "waiting" (AKA Time to First Byte) then it's probably the @Html issue.

**Comment by onionhammer** [comment]
No, this is a purely client-side issue, not server related at all. 99% of the time is spent in that function.

**Comment by Eilon** [comment]
@onionhammer can you perhaps send us the rendered HTML page (upload to GitHub somewhere), plus which browser version and  OS version you're using?

**Comment by ryanbrandenburg** [comment]
@onionhammer if you create a repro case for this feel free to reopen this, but I'm closing it until then.
