### ISSUE TITLE
This project is under Apache but the nuget package is licensed under a different license?

### ISSUE THREAD

**Issue by omajid** [aspnet/jquery-validation-unobtrusive#140]
The `LICENSE.txt` file says this project is under Apache 2.0.

But the NuGet package says it's under the (non-Open Source) "MICROSOFT .NET LIBRARY" license:

https://github.com/aspnet/jquery-validation-unobtrusive/blob/95c686bc6c64538d41d45080975b861cf7e8076b/Microsoft.jQuery.Unobtrusive.Validation.nuspec#L11

Is this intentional?

**Comment by omajid** [comment]
cc @dleeapho @leecow

**Comment by omajid** [comment]
cc @dseefeld @MichaelSimons @crummel

**Comment by Pilchie** [comment]
Also tagging @ChrisSfanos.

**Comment by richlander** [comment]
Ping ... Can we make this happen for .NET 7?

**Comment by dougbu** [comment]
Adding @mkArtakMSFT as well.

I remember discussing this issue a few weeks ago but don't recall the upshot. Suggest we wait for @Pilchie's return from vacation.

**Comment by richlander** [comment]
@ChrisSfanos is going to resolve this for us.
