### ISSUE TITLE
Ability to change field-validation class names

### ISSUE THREAD

**Issue by robstruthers** [aspnet/jquery-validation-unobtrusive#151]
I am currently using jquery-validation-unobtrusive with a Bootstrap 5 site. By changing the options I can get the input fields to work with bootstrap without any additional work by doing the below: 

```
var settings = {
    validClass: "is-valid",
    errorClass: "is-invalid"
    
};
```

The issue I am having is that the error messages displayed below the input fields are wrapped in `field-validation-valid` and `field-validation-invalid` classes but, I can not find anywhere that these class names can be changed. If this were possible it would then be straightforward to overwrite them to the Bootstrap class names of `valid-feedback` and `invalid-feedback`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're not making any improvements in this area any more as this project is in maintenance mode. Only critical blocking issue with wide impact and security issues are considered.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're not making any improvements in this area as we prefer to work on more important areas of the framework instead. Only critical blocking issue with wide impact and security issues are considered.
