### ISSUE TITLE
This version can't find the correct place to put error message

### ISSUE THREAD

**Issue by jcspader** [aspnet/jquery-validation-unobtrusive#19]
When I define the tag span to receive error validation message, this plugin can't find the correct element to work.

For test, you can use this page:

```
<form action="/" id="formTeste" method="get" novalidate="novalidate">

    <span class="field-validation-valid" data-valmsg-for="field2" data-valmsg-replace="true"></span>    

    <div>
         <label for="field1">field1</label>
         <input id="field1" name="field1" required="required" type="text" value="" />
         <span class="field-validation-valid" data-valmsg-for="field1" data-valmsg-replace="true" required="required"></span>
    </div>

    <div>
         <label for="field2">field2</label>
         <input id="field2" name="field2" required="required" type="text" value="" />
    </div>

   <button type="button">Submit</button>

</form>

<script type="text/javascript">
    $(document).ready(function () {
        $("#formTeste button").on("click", function () {
            $("#formTeste").valid();
        });
    });
</script>
```

When submitting, it creates a new element down the field, ignoring tag span `` data-valmsg-for="field2" `` already defined

In past versions work properly.
https://www.nuget.org/packages/jQuery.Validation.Unobtrusive/2.0.20710

![image](https://cloud.githubusercontent.com/assets/1699660/11817405/e7c4b992-a33b-11e5-9b17-e5ac6de51b57.png)

**Comment by dougbu** [comment]
@jcspader please add the generated HTML (i.e. view source in your browser) and the HTML you expected.

**Comment by jcspader** [comment]
@dougbu 
```
<form action="/" id="formTeste" method="get" novalidate="novalidate">

    <span class="field-validation-valid" data-valmsg-for="field2" data-valmsg-replace="true"></span>    

    <div class="form-control">
         <label for="field1">field1</label>
         <input id="field1" name="field1" required="required" type="text" value="" />
         <span class="field-validation-valid" data-valmsg-for="field1" data-valmsg-replace="true" required="required"></span>
    </div>

    <div class="form-control">
         <label for="field2">field2</label>
         <input id="field2" name="field2" required="required" type="text" value="" />
    </div>

   <button type="button">Submit</button>

</form>

<script type="text/javascript">
    $(document).ready(function () {
        $("#formTeste button").on("click", function () {
            $("#formTeste").valid();
        });
    });
</script>

```

**Comment by dougbu** [comment]
@jcspader I must be missing the issue. Other than `required="required"` showing up in the `<span>` for `field1`, the generated code looks as I expect. There is just one `<span>` per `@Html.ValidationMessage()` call. What were you expecting to be different?

**Comment by jcspader** [comment]
In the original version, when I create the Html.ValidationMessage element of Asp.NET MVC, the message is included into the element.

In the current version, it creates a new element down the field and ignore the correct element.

![image](https://cloud.githubusercontent.com/assets/1699660/11817405/e7c4b992-a33b-11e5-9b17-e5ac6de51b57.png)

**Comment by dougbu** [comment]
Got it. The `jquery-validation-unobtrusive` code is creating `<span>` elements instead of using the existing ones. That is, it's not finding the elements with `data-valmsg-for="field1"` or `data-valmsg-for="field2"` attributes. Then `container` is an empty jQuery element after https://github.com/aspnet/jquery-validation-unobtrusive/blob/master/jquery.validate.unobtrusive.js#L42. Likely `this` references an unexpected element when `OnError()` is invoked.

**Comment by ryanbrandenburg** [comment]
After consulting with @Eilon we've concluded that it's expected that jquery-validation-unobtrusive won't do anything when you aren't using the model syntax. An example of that is here https://github.com/aspnet/Mvc/blob/f0777b95a84583477bc53426e438116f0a0673e3/test/WebSites/TagHelpersWebSite/Views/Employee/Create.cshtml

As a note, your `new { required = "required"}` syntax is a part of jquery.validation and html5, but is not a part of jquery.validation.unobtrusive, which may be where some of the confusion came from..

**Comment by jcspader** [comment]
> As a note, your new { required = "required"} syntax is a part of jquery.validation and html5, but is not a part of jquery.validation.unobtrusive, which may be where some of the confusion came from..

@ryanbrandenburg Sorry, but I think you did not read the history. I did a full HTML template and the error was found at @dougbu and add Bug tag by @Eilon.

Look the comment:
https://github.com/aspnet/jquery-validation-unobtrusive/issues/19#issuecomment-164722596

**Comment by ryanbrandenburg** [comment]
@jcspader I did read the history, and again just now to ensure I didn't miss anything. I also plugged the example from your comment into a site and found that the behavior was the same whether jquery.validation.unubtrusive.js was included or not.

@dougbu did I miss something here?

**Comment by jcspader** [comment]
@ryanbrandenburg 
In short, after the latest changes of the plugin as the [comment ](https://github.com/aspnet/jquery-validation-unobtrusive/issues/19#issuecomment-164825953)of the image, Unobtrusive plugin is not locating the correct element to put the validation message.

**Comment by Eilon** [comment]
@jcspader I think there's some confusion here around the three validation systems:

1. HTML5 looks at the `required="required"` attributes, though they are disable with the `novalidate = "novalidate"` attribute.
2. jQuery Validation also looks at the `required="required"` attributes and processes them, and it creates *its own* HTML labels/spans to show its errors.
3. jQuery Unobtrusive Validation looks at the `data-val-***` attributes (and *only* those attributes) and uses the `<span>` elements generated by `@Html.ValidationMessage(...)`. This library uses jQuery Validation, but does not work with jQuery Validation's or HTML5's attributes.

The thing I think we want to be sure of is that only one validation system is being used at a time. If more than one system's settings and features are being used then the behavior will be unexpected.

**Comment by Eilon** [comment]
@jcspader from my understanding of the behavior you're seeing (and I looked at it together with @ryanbrandenburg), the extra weird message you see if coming from jQuery Validation looking at the `required="required"` attribute - and that is not related to jQuery Unobtrusive Validation.

If you remove all the HTML5 attributes from the code do you get the behavior you expect?

**Comment by jcspader** [comment]
@Eilon  The Tag @Html.ValidationMessage(...) is because a copy my code asp.net mvc.

After I posted the code HTML + JS.
Please, forget the code from first comment.

**Comment by jcspader** [comment]
> The thing I think we want to be sure of is that only one validation system is being used at a time. If more than one system's settings and features are being used then the behavior will be unexpected.

@Eilon The Tag @Html.ValidationMessage(...) is because a copy my code asp.net mvc.

After I posted the code HTML + JS.
Please, forget the code from first comment.

**Comment by Eilon** [comment]
@jcspader my current suspicion is still that it's jQuery Validation creating its own element and doesn't use the other error message elements.

But I'm happy to be wrong about this too :smile:

**Comment by ryanbrandenburg** [comment]
@jcspader I've consulted with @dougbu and tweaked your earlier sample into working order:
```
@model MvcSandbox.Models.Employee

@using (Html.BeginForm("", "", FormMethod.Get, new { id = "formTeste" }))
        {
            @Html.ValidationMessage("Field2")

            <div class="form-control">
                @Html.Label("Field1")
                @Html.TextBox("Field1")
                @Html.ValidationMessage("Field1")
            </div>

            <div class="form-control">
                @Html.Label("Field2")
                @Html.TextBox("Field2")
            </div>

            <button type="button">Submit</button>
        }
```

Importantly, @dougbu pointed out that you likely were using the model but just left that out of the sample, so I've explicitly added it. Also of note is that casing DOES matter here (I thought it didn't which caused some confusion) and thirdly I've removed all the html attribute stuff which was clouding the matter. When I do all these things the page behaves as expected and with the span up top being used to show the message.

Once I understood that you probably had a model but had left it out it all made sense, sorry for the confusion and I hope that gets you solved.

**Comment by jcspader** [comment]
Guys, I change the first post and removed the ASP.NET MVC code to end the confusion.

**Comment by Eilon** [comment]
Re-opening for discussion.

@jcspader if you're still seeing an issue, is there any chance you can share more of your page/controller/model so we can make sure we're trying out the exact same scenario?

Sorry for all the confusion around this!

**Comment by ryanbrandenburg** [comment]
@jcspader, it's been a couple days so I'm going to close this one. If you're still not solved and can provide your page/controller/model or other useful info feel free to re-open it, otherwise I hope we got you fixed.
