### ISSUE TITLE
Validation fails for float and decimal for non english format

### ISSUE THREAD

**Issue by pierre-weceipt** [aspnet/jquery-validation-unobtrusive#27]
The script is failing validation for float and decimal inputs if the numbers is not in English format (with `.` as decimal separator). It should be able to accept other separators or use the locale values.

**Comment by blogcraft** [comment]
I  have the same issue, here in Chile we have `,` as decimal separator and the validation always fails on the client side. Validation should adapt to the localization of the client. So my app works no matter what regional config is available in the browser

**Comment by blogcraft** [comment]
I found there is a simple way to fix this, just add globalize and jquery-validate-globalize and it will work.

   ```
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/globalize/lib/globalize.js"></script>
<script src="~/lib/jquery-validation-globalize/jquery.validate.globalize.js"></script>
```

**Comment by pierre-weceipt** [comment]
It's working, I'm closing the issue

**Comment by Luther-Varys** [comment]
how did you add the cultures to globalize?

**Comment by pierre-weceipt** [comment]
Sorry for the late answer. I just added the scripts and it just "worked" but I don't know how as I latter used globalize somewhere else and had to do lot of config and import the culture jsons as described in globalize doc.
