### ISSUE TITLE
Does the unhighlight and highlight callback exists?

### ISSUE THREAD

**Issue by Eneuman** [aspnet/jquery-validation-unobtrusive#29]
Hi!
I'm trying to use the highlight and unhighligt callback that exists in the jQuery Validation plugin but these does not seem to work with this unobtrusive plugin. Is it me or are they not implemented yet?

Regards
Per

**Comment by Eilon** [comment]
Hmm I'm not familiar with these callbacks. What are you expecting it to do?

**Comment by Eneuman** [comment]
In the jQuery Validation plugin (http://jqueryvalidation.org/validate/) they have callbacks that lets you run you own code when certain things happens. Two of theese events are highlight and unhighlight.
Theese lets you override the presentation of invalid fields like this:

    $(".selector").validate({
     highlight: function(element, errorClass) {
       $(element).fadeOut(function() {
          $(element).fadeIn();
       });
     }
    });

I would like to be able to do the same thing when using the unobstrusive validation js files in the ASP.Net Core Project Template :)

**Comment by Eilon** [comment]
Not planning to support that at this time.

**Comment by mikes-gh** [comment]
Heres an example of how to setDefaults when using unobtrusive
Put this at the end of your _ValidationScriptsPartial.cshtml

This example uses Highlight and Unhighlight callbacks for bootstrap styling.
Note if you want to set invalidHandler for clever focus or something you need to set it at the unobtrusive level as unobtrusive overites jquery.validate for this option.

Its all very confusing.
It would be nice if unobtrusive had a copy of all the jquery.valdate options and passed them on.
Currently its difficult to know where to set the options as unobtrusive doesnt support a lot of options and overites some.

```
<script>
    var defaultOptions = {
        highlight: function (element, errorClass, validClass) {
            $(element).closest(".form-group").addClass(errorClass);

        },
        unhighlight: function (element, errorClass, validClass) {
            $(element).closest(".form-group").removeClass(errorClass);
        },
        focusInvalid: false
    };

    $.validator.setDefaults(defaultOptions);

    $.validator.unobtrusive.options = {
        errorClass: 'has-error',
        invalidHandler: function (e, validator) {
            try {
               alert('invlaidHandler needs to be set here not in jquery.validate');

                // Manually trigger focusin event; without it, focusin handler isn't called, findLastActive won't have anything to find
                .trigger("focusin")
            }
            catch (e) {

                // Ignore IE throwing errors when focusing hidden elements
            }
        }
    }

    $(function () {
        $("span.field-validation-valid, span.field-validation-error").addClass('help-block');
    });
</script>
```

**Comment by polishninja** [comment]
I've found that if you set the default options before loading the unobtrusive script, it will work. Here I've placed the semantic.validation.js after the jquery.validate.js but before the jquery.validate.unobtrusive.js script.

` <script src="~/lib/jquery/dist/jquery.js"></script>`
`<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>`
**`<script src="~/js/semantic.validation.js"></script>`**
`<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>`

### semantic.validation.js
```
$(function () {
    if ($.validator) {
        $.validator.setDefaults({
            highlight: function (element, errorClass, validClass) {
                $(element).closest('.field').addClass('error');
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).closest('.field').removeClass('error');
            }
        });
    }
});
```
Found this solution in the [OminSharp Project](https://github.com/OmniSharp/generator-aspnet/tree/master/templates/overrides/semantic/mvc)
