### ISSUE TITLE
When I reference this project in my website do I still need to reference Jquery validate?

### ISSUE THREAD

**Issue by ricardopolo** [aspnet/jquery-validation-unobtrusive#30]
Or having jquery-validation-unobtrusive I will have all the methods available in jquery.validate.min.js?

Thanks!

**Comment by Eilon** [comment]
Yes, when using this JS file you need to reference both jQuery and jQuery Validate.

If this file is being included in the project through a package manager (e.g. npm, bower, etc.) then all the required dependencies should be automatically installed.
