### ISSUE TITLE
Please publsh yourself in CdnJs

### ISSUE THREAD

**Issue by ricardopolo** [aspnet/jquery-validation-unobtrusive#31]
https://github.com/cdnjs/cdnjs/issues/7176

**Comment by Eilon** [comment]
Will revisit at a later time, thanks.

**Comment by ricardopolo** [comment]
Done

**Comment by Eilon** [comment]
We can keep this open so we don't forget.

**Comment by ricardopolo** [comment]
No @Eilon I mean the issue has been done

If you go to  https://cdnjs.com/ you can double check the jquery validate unobstrusive  is there.
They do it in this commit https://github.com/cdnjs/cdnjs/commit/62ccaba830a4914dfa4bb4687a5fb6b6a78fa3f9, it uses NPM autoupdate so you can forget about it.

**Comment by Eilon** [comment]
Oh, well than thank you very much! :smile: I'll mark this issue as completed.
