### ISSUE TITLE
Localization unobtrusive

### ISSUE THREAD

**Issue by SanteR1** [aspnet/jquery-validation-unobtrusive#32]
Hello, I use mvc.net 5 and jquery-validation-unobtrusive, jquery-validation(localization)
For localization error message i use lib 
https://github.com/jzaefferer/jquery-validation
But localization not work with your lib jquery-validation-unobtrusive
I test why not work this issue
https://github.com/jzaefferer/jquery-validation/issues/1736
Whether it is possible to correct it and to add a feature for interaction with this library?

**My test post**
Hello, I test file jquery.validate.unobtrusive.js (rename to txt for attach)
[jquery.validate.unobtrusive.txt](https://github.com/jzaefferer/jquery-validation/files/170958/jquery.validate.unobtrusive.txt)
in the line 212 - message: message,
I replace to - message: "",
Then error message localization fo me, this fine work ...

**You can make changes to your library what it would clean off messages the created jquery.validate.unobtrusive?
Many probably face it when using asp.net mvc 5**

And one more test
https://jsfiddle.net/SanteR1/p54vravj/
If clear `data-val-required="The field Название is required"`
to
`data-val-required=""`
and run jsfiddle test then error message is localization to russian (or in any other localization, depending on connection of message_##.js)

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, can you please look into this? Not sure I clearly understand the issue, though.

**Comment by ryanbrandenburg** [comment]
@SanteR1 I need more information about what exactly you're trying to do, especially since I'm not framiliar with jquery localization concepts and patterns. Why do you need to include messages both in the `data-val-required` area and in your localizer? Why not just do `data-val-required id="Title"` and have the property without any value?

**Comment by ryanbrandenburg** [comment]
Closing as needs more info. If you're still having an issue here feel free to re-open with more info.
