### ISSUE TITLE
Name attributes containing brackets does not work

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/jquery-validation-unobtrusive#33]
When using `[` and `]` in the `name` attribute then it does not find the `data-valmsg-for` element to put the error message in.

`name=Foo.0.Bar` works, but `name=Foo[0].Bar` does not work.

### Functional impact
Validation does not work for input fields with a `name` attribute containing brackets.
If the developer can't use brackets, then receiving data into a view model gets impossible in situations where the form is dynamically generated and contain a dynamic amount of input fields.

### Minimal repro steps
https://jsfiddle.net/tbb6u0cd/
```html
<form method="post">
  <input data-val="true" data-val-required="" name="Foo[1].Alternatives[1].Selected" class="hello" type="text">
  <span class="field-validation-valid" data-valmsg-for="Foo[1].Alternatives[0].Selected" data-valmsg-replace="true"></span>
  <input type="submit" value="Create" />
</form>

<form method="post">
  <input data-val="true" data-val-required="" name="Foo.0.Alternatives" type="text">
  <span class="field-validation-valid" data-valmsg-for="Foo.0.Alternatives" data-valmsg-replace="true"></span>
  <input type="submit" value="Create" />
</form>
```

### Expected result
The `data-valmsg-for` element is expected to contain the validation error message.

### Actual result
The `data-valmsg-for` element was blank and did not contain any error message.

### Further technical details
The `escapeAttributeValue` function escapes brackets, so I am not sure why it does not find the element.
https://github.com/aspnet/jquery-validation-unobtrusive/blob/master/jquery.validate.unobtrusive.js#L25

**Comment by ryanbrandenburg** [comment]
@vanillajonathan, the change I made to resolve this was incorrect and caused #39. Everything works on your jsfiddle if you change `data-valmsg-for="Foo[1].Alternatives[0].Selected"` to `data-valmsg-for="Foo[1].Alternatives[1].Selected"`. The problem was actually that your span was for an input element that didn't exist. Sorry for the confusion.

**Comment by vanillajonathan** [comment]
You are right. Sorry for the confusion and thanks for getting back to me.
