### ISSUE TITLE
Question: Should version be higher than 5.2.3?

### ISSUE THREAD

**Issue by dougbu** [aspnet/jquery-validation-unobtrusive#34]
The only versions for prior versions of jQuery Validation Unobtrusive line up with the MVC version they were released with (see [CDN listing](http://www.asp.net/ajax/cdn#ASPNET_MVC_Releases_on_the_CDN_16)). So the version before we created this repo was `5.2.3`.

The `npm` and `bower` packages we publish from here are version `3.2.6`. Is this lower version number going to confuse our customers? (I realize `5.2.3` was available only on nuget.org while this version is not available there. Nonetheless...)

**Comment by Eilon** [comment]
D'oh. The versions listed on that CDN page are wrong. But that ship has sailed. So, long story short, no, this is fine as far as the Bower/NPM/NuGet packages are concerned. It's just an issue with what they're called on the CDN.
