### ISSUE TITLE
Add latest files to http://ajax.aspnetcdn.com

### ISSUE THREAD

**Issue by dougbu** [aspnet/jquery-validation-unobtrusive#35]
Bug fixes made in this repo are not available to customers using the ASP.NET CDN. At least the  [CDN listing](http://www.asp.net/ajax/cdn#ASPNET_MVC_Releases_on_the_CDN_16) mentions only older versions of jQuery Validation Unobtrusive.

**Comment by XmlmXmlmX** [comment]
I use https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js

**Comment by mkArtakMSFT** [comment]
Closing this as the libraries are already available on CDN.
