### ISSUE TITLE
The equalto attributes do not work at all

### ISSUE THREAD

**Issue by bh3605** [aspnet/jquery-validation-unobtrusive#36]
See my stackoverflow question for reference: http://stackoverflow.com/q/37127178/2567273

Basically, the element the equalto-other attribute uses as a reference isn't being updated whenever the referenced element's value is changed causing the validation to ALWAYS be invalid.

I'm kinda surprised this hasn't been brought up sooner.

**Comment by Eilon** [comment]
@ryanbrandenburg can you find out what's going on here?

**Comment by ryanbrandenburg** [comment]
@bh3605 I was unable to reproduce this. [Here's](https://github.com/ryanbrandenburg/ValidationEqualTo) my repro app. Could you check to see that this still reproduces for you and create a similar minimum reproduction repository if it does?

**Comment by ryanbrandenburg** [comment]
Closing this as can't repro. If you can still reproduce please reopen with a reproduction app.
