### ISSUE TITLE
Validation summary ul

### ISSUE THREAD

**Issue by cjcfreitas** [aspnet/jquery-validation-unobtrusive#37]
By using `list = container.find("ul");`all `ul` tags inside the form will be selected.
If one uses a `ul` inside the form (e.g. FuelUX ComboBox) it will be reseted and filled with the error messages.
I suggest using an `id` for the error summary list: `list = container.find("#errorSummary");`.

**Comment by dougbu** [comment]
Why not find `ul` elements that are children of `div` elements with the `validation-summary-errors` class e.g. `div.validation-summary-errors>ul`? Can do the same for `ul` children of `div` elements with the `validation-summary-valid` class if those need to be handled as well.

**Comment by dougbu** [comment]
My apologies, you were looking at https://github.com/aspnet/jquery-validation-unobtrusive/blob/35546f7c49cfeb7947859e7292b5df402fce2471/jquery.validate.unobtrusive.js#L60

The `container` there is already the containing `div` and the `class` has already been verified. Cannot select all `ul` elements on the page or in the `form`.

**Comment by Eilon** [comment]
Hmm, yes, the code already looks to be written safely. I'm closing this issue for now.

@cjcfreitas if you can provide a detailed example of what HTML would cause a failure we can look at this again.

**Comment by cjcfreitas** [comment]
@dougbu and @Eilon:
You are absolutely right.
The reason I had the issue was because I was using a self closing div as a container. I failed to notice that previously. Sorry for wasting your time. Many thanks.

**Comment by Eilon** [comment]
@cjcfreitas thanks! BTW self-closing `<div>` tags are not valid HTML (it's super annoying!).
