### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by ricardopolo** [aspnet/jquery-validation-unobtrusive#41]
Jquery validation just release a new version

https://github.com/jzaefferer/jquery-validation/issues/1798

Please release a new version of jquery validation unbostrusive

**Comment by Eilon** [comment]
@ricardopolo assuming that jQuery Validation remains backwards-compatible, there shouldn't be a need to release a new version of jQuery Validation Unobtrusive.

Do you have a specific request here?

**Comment by ricardopolo** [comment]
Oh, I thought, you are just a wrapper of the public jquery val.

@codingneat can you tell use please about this requeriment? What is wrong with the old version of jquery that doesnt allow summernoote work propertly?

Thanks

**Comment by Eilon** [comment]
@ricardopolo nope, the jQuery Unobtrusive Validation we have here is an add-on library that depends on jQuery Validation (and jQuery).
