### ISSUE TITLE
Minify js as part of build

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/jquery-validation-unobtrusive#43]
Currently we rely on people manually minifying the file, we should add a git hook or a build.cmd or something which minifies the js automatically so the `.js` and `.min.js` don't get out of step.

**Comment by Eilon** [comment]
All yours 😄 Make sure that whatever we do to automate this is xplat-friendly.

**Comment by javiercn** [comment]
No git hook. You should work with @pranavkm to add it to the build steps. Ideally we should produce the minified versions on each build and not have them check-in.

**Comment by pranavkm** [comment]
We used to do mininfication with TagHelper scripts in Mvc as part of the build (we stopped doing this because we didn't want npm \ gulp to run as part of Mvc's build). We could do something similar here.

**Comment by Eilon** [comment]
I think we need the minified files checked in because that's how Bower works.

**Comment by ryanbrandenburg** [comment]
If the minified version must be checked in to git for bower to consume then a git hook is the only way I can think of to ensure it gets minified. I'll make that my plan unless I hear otherwise.

**Comment by Eilon** [comment]
Just do it on build, no? Does this need to be any more complicated?

**Comment by pranavkm** [comment]
The way we do with PageGenerators? Check in the minified file and have a way for the build to produce one?

**Comment by Eilon** [comment]
Yeah wouldn't that be like ultra trivial?

**Comment by pranavkm** [comment]
Yup. It's just manual work you'd have to remember to do anytime the file is modified. Maybe we could update the README to say this.

**Comment by xt0rted** [comment]
Why not put all of this into gulp [like bootstrap does](https://github.com/twbs/bootstrap/blob/7e2741eb1074afc66bdf2fb5c2b65d476cf7f37e/Gruntfile.js#L510)? Then to do a new release you'd just run this, commit, and then add a release to the repo. You could even have gulp do it all for you https://gist.github.com/eseceve/1461a561b4184dd6e2da

**Comment by Eilon** [comment]
@xt0rted yeah I think that's the same idea as what we want, but I think what we need here is somewhat simpler because it's just 1 file. But yeah basically we need to just run gulp and commit.

**Comment by Eilon** [comment]
Done?

**Comment by RehanSaeed** [comment]
The minified script is not contained in the NPM package. I've raised [this](https://github.com/aspnet/jquery-validation-unobtrusive/issues/48) with [this](https://github.com/aspnet/jquery-validation-unobtrusive/pull/49) PR to fix this problem.
