### ISSUE TITLE
Updating jQuery Unobtrusive Ajax scripts

### ISSUE THREAD

**Issue by Eilon** [aspnet/jquery-validation-unobtrusive#47]
_From @rustd on April 6, 2016 20:36_

We are using these scripts in MVC 5 as well. Today we are only updating them in bower and npm.
Should we update the NuGet package (https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Ajax/) for MVC 5 as well.

_Copied from original issue: aspnet/Mvc#4420_

**Comment by Eilon** [comment]
_From @danroth27 on April 12, 2016 16:54_

@DamianEdwards Thoughts on this?

**Comment by DamianEdwards** [comment]
If they're fully compatible, then sure. But it might be better to do it as part of the wider MVC 5.x updates we plan on doing.

**Comment by Eilon** [comment]
@DamianEdwards yeah that comment was actually from 6 months ago 😄 But yes I agree.

**Comment by ryanelian** [comment]
Any estimate when the new scripts will be published to NPM / nuget?

**Comment by mkArtakMSFT** [comment]
@jbagga , can you please look into this? Thanks!

**Comment by jbagga** [comment]
For cdnjs, auto-update has been set up https://github.com/cdnjs/cdnjs/pull/7332 via npm

**Comment by jbagga** [comment]
@Eilon @mkArtakMSFT The build scripts are in place for the next release for aspnet/jquery-validation-unobtrusive and aspnet/jquery-ajax-unobtrusive. Removing the Working label for now.

**Comment by mkArtakMSFT** [comment]
Closing this as this has been resolved as part of some other effort. We now have the drop targets defined at: https://github.com/aspnet/jquery-validation-unobtrusive/wiki/Release-checklist
