### ISSUE TITLE
Update Microsoft.jQuery.Unobtrusive.Validation to version 3.2.3

### ISSUE THREAD

**Issue by radiok** [aspnet/jquery-validation-unobtrusive#5]
NuGet [Microsoft.jQuery.Unobtrusive.Validation](https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Validation) has had a new version since February 9, 2015.  Could you please update GitHub with the latest release?  Thank you!

**Comment by radiok** [comment]
I resolved this myself with 77eaf1715113a61764071ada7c5c998f6c414644 if you just want to merge.

**Comment by Eilon** [comment]
@danroth27 let's make sure we include this repo in our triage. Looks like we should take this so let's discuss tomorrow.

@rustd would we need to update the templates with the new version?

**Comment by vkrol** [comment]
+1

**Comment by Eilon** [comment]
@kichalla please work with @rustd to see if templates need to be updated to use this new version.

**Comment by rustd** [comment]
https://github.com/aspnet/Templates/issues/125 is tracking this for Beta8

**Comment by kichalla** [comment]
9a3a8478ed688a595e9a25eeb3f63559153acd64
