### ISSUE TITLE
Please Include Access-Control-Allow-Origin:* on Microsoft CDN

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/jquery-validation-unobtrusive#50]
The Microsoft CDN uses the Access-Control-Allow-Origin HTTP header inconsistently. Some scripts get it while others don't. I've tried a few avenues in getting this resolved and only managed to get the header added to bootstrap but not the unobtrusive script. The header should be added for two reasons:

`Access-Control-Allow-Origin:*`

1. Allows the `cross-origin` attribute to work and report more detailed errors from the script.
2. Allows the use of Subresource Integrity (SRI) to ensure that the CDN resource has not been tampered with.

**Comment by Eilon** [comment]
@blowdart is this your territory now? I know we've had lots of CORS issues with the CDN before.

**Comment by RehanSaeed** [comment]
I happened to reply to a tweet @blowdart made who sorted this issue pretty promptly.
