### ISSUE TITLE
Include version in file's header

### ISSUE THREAD

**Issue by denisz1** [aspnet/jquery-validation-unobtrusive#51]
Every js library includes the version in the file's header.

This library does not. And that means I always waste time trying to figure out the version, and make my build scripts work properly.

Please add the version, all it says now is this:

    /*!
    ** Unobtrusive validation support library for jQuery and jQuery Validate
    ** Copyright (C) Microsoft Corporation. All rights reserved.
    */

For example, jquery validation has this:

    /*!
     * jQuery Validation Plugin v1.15.1
     *
     * http://jqueryvalidation.org/
     *
     * Copyright (c) 2016 Jörn Zaefferer
     * Released under the MIT license
     */

**Comment by Eilon** [comment]
@kichalla please do the same for https://github.com/aspnet/jquery-ajax-unobtrusive as well.

BTW I wonder if it's possible to automate it somehow? E.g. have a token such as `%VERSION%` in the file, and read the version from `package.json` at build time?

**Comment by xt0rted** [comment]
I do this with gulp using `gulp-header` for all of my css & js.

```js
var header = require('gulp-header');

var pkg = require('./package.json');

var banner = [
    '/*!',
    ' * <%= pkg.name %> (<%= pkg.homepage %>)',
    ' * Copyright <%= pkg.copyright %> <%= pkg.author %>',
    ' * @version v<%= pkg.version %>',
    ' */',
    ''].join('\n');

gulp.task('less:build', function() {
    return gulp.src('./less/app/app.less')
        .pipe(sourcemaps.init())
        .pipe(header(banner, { pkg: pkg }))
        .pipe(less())
        .pipe(autoprefixer())
        .pipe(gulpif(release, cleanCSS()))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./content/css'));
});
```

**Comment by Eilon** [comment]
@xt0rted very nice, thanks! That looks like exactly what we need!
