### ISSUE TITLE
NPM version and milestone mess (out of sync)?

### ISSUE THREAD

**Issue by dotnetshadow** [aspnet/jquery-validation-unobtrusive#57]
Hi there,

I'm finding it very hard to work out what version of the library is included in the npm package.

When I specify version 3.2.6 I expect to see the minified version of the library in the npm package but I don't, Yet when I look at previous issues, it suggest that this has already been added to version 3.2.6 
See #48 

Are the versions and npm packages out of sync?

**Comment by VincentvD** [comment]
NPM version (3.2.6) seems to be the previous version 3.2.5.

**Comment by mathijsrave** [comment]
It seems that the 3.2.6 release is identical to the 3.2.5 release, even on the github release page.

**Comment by duncanmcdougall** [comment]
Is there any plans to get the UMD commit part of an official release (e.g. 3.2.7) and pushed to npm or has this repo been abandoned?

**Comment by mathijsrave** [comment]
@duncanmcdougall @VincentvD released the fixed version as a package on npm: https://www.npmjs.com/package/jquery-validation-unobtrusive-umd-fix

**Comment by Eilon** [comment]
This repo isn't abandoned but it hasn't been a high priority compared to other issues we've been working on.

**Comment by mkArtakMSFT** [comment]
Hi folks. It seems there was some issue on our end regarding how the packages were published. We're tracking the fix as part of https://github.com/aspnet/jquery-validation-unobtrusive/issues/66 issue. An additional fix will be made to make sure the NuGet packages contain the latest libraries going forward.
