### ISSUE TITLE
Validation cross different Cultures

### ISSUE THREAD

**Issue by joacar** [aspnet/jquery-validation-unobtrusive#59]
Hi,

When adding localization to my asp.net mvc core project the validation isn't synced. Request the `en-US` version of a page handles the input `2,5%` correctly in that it should be `2.5%`.

However, resorting to swedish `se-SV` the input `2,5%` is interpreted as incorrect.

Search for any previous issues regarding this but couldn't find any. Most probable cause is bad search words, since this feel like a topic that has been discussed previously :)

Thanks

**Comment by danroth27** [comment]
Have you included client side globalization libraries for the cultures you want to support? Take a look at the "Globalized JavaScript Validation" section of this blog post to see how this is done.

**Comment by joacar** [comment]
Haven't done that.. Will check it out, thanks!

**Comment by joacar** [comment]
@danroth27 At my desktop now and you must have missed to include the url to the blog post. Thought it was just a rendering issue on the phone at first.

Doing some proper googling resulted in [this](https://github.com/johnnyreilly/jquery-validation-globalize) and ~~[this](https://github.com/johnnyreilly/jQuery.Validation.Unobtrusive.Native)~~ (asp.net/webforms) both by John Reilly. 

Is it the first one you had in mind?

**Comment by danroth27** [comment]
Sorry about that - here is the Scott Hanselman post I meant to include: http://www.hanselman.com/blog/GlobalizationInternationalizationAndLocalizationInASPNETMVC3JavaScriptAndJQueryPart1.aspx.

**Comment by ClausSuperusers** [comment]
@joacar Did You find a (simple) solution to this issue?
I've got the same problem and Scott Hanselman's information are related to a very old version of MVC - I don't recall having this issue with MVC4 or 5.
It DOES seem to be related only to the Client side validation....

**Comment by joacar** [comment]
@ClausSuperusers 

Unfortunately not. I haven't had the time to write document the steps, so here you go

Below is only for `number.js` so add more modules if needed.
```
<script src="~/lib/cldrjs/dist/cldr.js"></script>
<script src="~/lib/cldrjs/dist/cldr/event.js"></script>
<script src="~/lib/cldrjs/dist/cldr/supplemental.js"></script>
<script src="~/lib/globalize/dist/globalize.js"></script>
<script src="~/lib/globalize/dist/globalize/number.js"></script>
<script src="~/lib/jquery-validation-globalize/jquery.validate.globalize.js"></script>
```

I currently load them on page load like this
```
<script type="text/javascript">
    $(document).ready(function () {
        const culture = $("html").attr("lang");
        var locale = culture.split("-")[0];

        $.when(
            $.getJSON("/lib/cldr-data/supplemental/likelySubtags.json"),
            $.getJSON(`/lib/cldr-data/main/${locale}/numbers.json`),
            $.getJSON("/lib/cldr-data/supplemental/numberingSystems.json")
        )
            .then(function () {
                console.log("Handle cldr-data response");
                return [].slice.apply(arguments, [0]).map(function (result) {
                    console.log("Map cldr-data response");
                    return result[0];
                });
            })
            .then(Globalize.load)
            .then(function () {
                Globalize.locale(locale);
                console.log(`Locale set to '${locale}'`);
            });
    });
</script>
```

What I would like to figure out and write about is how to create a tool that 

1. Take a list of supported cultures
2. Downloads the necessary `cldr-data` files
3. Create a `localized.min.js` or alternatively `app.{locale}.min.js`
4. Make the JSON files compact and embed in response
