### ISSUE TITLE
NuGet version uses andSelf instead of addBack

### ISSUE THREAD

**Issue by sergeydgr8** [aspnet/jquery-validation-unobtrusive#63]
Refer to: https://github.com/jquery-validation/jquery-validation/issues/1997

> The method `andSelf` was deprecated back in version 1.8 of jQuery and instead used as an alias for `addBack`. This plugin uses `andSelf` in `parse()` of the unobtrusive version of the validator. It works fine in older versions in jQuery, however, beginning jQuery 3.0, `andSelf` is removed completely: https://api.jquery.com/andSelf/
>
> The fix for this is just to replace `andSelf` with `addBack` in the parse function. The validator then works as it should under jQuery 3.

It seems like this repo doesn't have the issue. However, the version that is hosted on NuGet does have it.

**Comment by mkArtakMSFT** [comment]
@jbagga, can you please handle this?

**Comment by jbagga** [comment]
@sergeydgr8 Version 3.2.4 does not have any instances of andSelf https://github.com/aspnet/jquery-validation-unobtrusive/blob/v3.2.4/jquery.validate.unobtrusive.js which is the latest on NuGet.
Which version are you using?

**Comment by jbagga** [comment]
@sergeydgr8 Closing for now. Please feel free to reopen this with more information, if needed!

**Comment by sergeydgr8** [comment]
SGTM. I haven't used this in a while and the project that I needed this on is no longer maintained.
