### ISSUE TITLE
 How the message changes according to the current culture with asp.net core ? 

### ISSUE THREAD

**Issue by SertacEren** [aspnet/jquery-validation-unobtrusive#65]

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@kichalla, is there any documentation or post we can refer to?

**Comment by mkArtakMSFT** [comment]
Closing as this was just a question asked a while ago.
