### ISSUE TITLE
The minified bundle version is not published to NPM

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/jquery-validation-unobtrusive#66]
You've already fixed a problem with missing minified bundle inclusion in NPM:
https://github.com/aspnet/jquery-validation-unobtrusive/issues/48
but the updated NPM definition was never used to update version on NPM, so people are downloading version without minified content I think.
Related:
https://github.com/aspnet/jquery-validation-unobtrusive/issues/57

**Comment by mkArtakMSFT** [comment]
@kichalla , can you please look into this when you'll be back.

**Comment by kichalla** [comment]
I have now published a new version (3.2.8) to npm registry having the minified file and a minor fix (https://github.com/aspnet/jquery-validation-unobtrusive/issues/74).

**Comment by Eilon** [comment]
@kichalla / @mkArtakMSFT - we've worked with @jbagga to come up with a release plan for these packages. Did we do everything we need to do for this release?
