### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by giggio** [aspnet/jquery-validation-unobtrusive#7]
Right now it is only on bower. Publish to NPM, that is the recommended way to deploy jquery plugins now.

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by mediafreakch** [comment]
+1 (adding a package.json makes sense anyway)

**Comment by Eilon** [comment]
@kichalla please talk to @DamianEdwards about how to set this up.

**Comment by mogusbi** [comment]
Is this ever going to get published to npm?

**Comment by kichalla** [comment]
I checked for the following bower.json(from asp.net 5 web template) packages if they are present in the npm registry...

```
{
  "name": "ASP.NET",
  "private": true,
  "dependencies": {
    "bootstrap": "3.0.0",
    "bootstrap-touch-carousel": "0.8.0", // not present in npm registry
    "hammer.js": "2.0.4",
    "jquery": "2.1.4",
    "jquery-validation": "1.11.1", // not present in npm registry
    "jquery-validation-unobtrusive": "3.2.2" // not present in npm registry
  }
}
```

**Comment by glacasa** [comment]
jquery-validation 1.14 is present in npm registry 
https://www.npmjs.com/package/jquery-validation

**Comment by giggio** [comment]
@glacasa That is not jquery-validation-unobstrusive.

**Comment by glacasa** [comment]
@giggio it was an answer to @kichalla, who said that jquery-validation was not present in npm registry.

jquery-validation-unobstrusive is still missing

**Comment by kichalla** [comment]
41bf5b4c4d8bcf44dd810bf3bf96cc87f2c49315

**Comment by giggio** [comment]
Is this the official package? https://www.npmjs.com/package/jquery-validation-unobtrusive

**Comment by kichalla** [comment]
Yes
