### ISSUE TITLE
Have this package available on CDNJS

### ISSUE THREAD

**Issue by Eilon** [aspnet/jquery-validation-unobtrusive#76]
See https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md for how to make this happen.

**Comment by Eilon** [comment]
Tagging @DamianEdwards @jbagga FYI

**Comment by li0nsar3c00l** [comment]
would like to see this too

**Comment by mkArtakMSFT** [comment]
This is handled as part of the `Release checklist` we've put together for this repo.

**Comment by mkArtakMSFT** [comment]
The package is available on CDNJS already: https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js
