### ISSUE TITLE
Why asp.net vnext still focused in jQuery Validation at client side?

### ISSUE THREAD

**Issue by alexsandro-xpt** [aspnet/jquery-validation-unobtrusive#8]
Today we have Angular Validation too. We should not have an angular - validation- unobtrusive too ?

**Comment by nathanboktae** [comment]
Putting your business logic in HTML attributes in a view is a huge anti-pattern. This project should be killed with fire. See [Knockout-Validation](https://github.com/Knockout-Contrib/Knockout-Validation) for a proper separation of concerns where business logic is in code.

**Comment by danroth27** [comment]
There are certainly other client frameworks that you can use for validation, but we think jQuery Validation is still pretty popular.
