### ISSUE TITLE
Make Webpack as part of the build process to catch any errors

### ISSUE THREAD

**Issue by kichalla** [aspnet/jquery-validation-unobtrusive#85]
This is so that we can avoid errors like these https://github.com/aspnet/jquery-validation-unobtrusive/issues/79

cc @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
> Would it essentially be sort of a test? That is, we wouldn't be using webpack for any part of the build process, but we'd run it to make sure it doesn't fail?

Yes @Eilon

**Comment by kichalla** [comment]
54ce1311a56792b1e885ede47de1a84273cb9d69
