### ISSUE TITLE
current version is not working

### ISSUE THREAD

**Issue by JohnsonYuan** [aspnet/jquery-validation-unobtrusive#92]
When I put current jquery.validate.unobtrusive.js to page, throws error:

Uncaught TypeError: Cannot set property 'unobtrusive' of undefined
`
(function (factory) {
       // set jquery.validate.unobtrusive
}(function ($) {
      var $jQval = $.validator,
        adapters,
        data_validation = "unobtrusiveValidation";

    $jQval.unobtrusive = {                   // this line throws exception

    };

   //...
}));

the factory parameter we passed is a function **function ($) {}**, but the parameter $ is not assigned and throws the error.

`

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
