### ISSUE TITLE
package.json points to old(?) license

### ISSUE THREAD

**Issue by hsaunders0788** [aspnet/jquery-validation-unobtrusive#93]
The package.json and bower.json files point to a Microsoft license ("https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm"), but the LICENSE.txt clearly states that this package is available under the Apache-2.0 license, which the .NET Core package is also licensed under. This makes it confusing as to which license is the relevant license.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hsaunders0788.
@danroth27, can you please look into this? Thanks!
/cc @ryanbrandenburg

**Comment by javiercn** [comment]
This was done or points to the right place now: https://aka.ms/jqueryunobtrusivelicense
