### ISSUE TITLE
$.validator.addMethod is ignored when trying to add custom validation rules

### ISSUE THREAD

**Issue by CrestApps** [aspnet/jquery-validation-unobtrusive#96]
I am trying to add a new rule called `filesize` which inspects the size of the attached file.

If the file's size if greater than the allowed, I want to show client size error message.

I created [FileSizeAttribute](https://github.com/CrestApps/MvcWithUnobtrusive/blob/master/MvcWithUnobtrusive/FileSizeAttribute.cs) attribute to be able to use in my view-models to decorate my `HttpPostedFileBase` properties with to set the max allowed size. The [CreatePerson](https://github.com/CrestApps/MvcWithUnobtrusive/blob/master/MvcWithUnobtrusive/ViewModels/CreatePerson.cs) class show how I am consuming it.

Then in my javascript files, I added the following code  to register a new method called [filesize](https://github.com/CrestApps/MvcWithUnobtrusive/blob/master/MvcWithUnobtrusive/Scripts/jquery.validate.setup.js#L32-L58) in the validator.

```
$.validator.addMethod("filesize", function (value, element, param) {

        if (value === "") {
            return true;
        }

        var maxBytes = parseInt(param);

        if (element.files !== undefined && element.files[0] !== undefined && element.files[0].size !== undefined) {
            console.log('Dumping the file object', lement.files[0]);

            var filesize = parseInt(element.files[0].size);

            return filesize <= maxBytes;
        }
        return true;
});
```

Then I added a new unobtrusive adapter called [filesize ](https://github.com/CrestApps/MvcWithUnobtrusive/blob/master/MvcWithUnobtrusive/Scripts/jquery.validate.setup.js#L60-L74) to allow me to add the rule/message to the validation options like so 

```
    $.validator.unobtrusive.adapters.add('filesize', ['maxfilesize'], function (options) {
        // set the parameter
        options.rules['filesize'] = options.params.maxfilesize;

        if (options.message) {
            // If there is a message, set it for the rule
            options.messages['filesize'] = options.message;
        }
});
```

I can see the the adapter is being registered, but the method [filesize](https://github.com/CrestApps/MvcWithUnobtrusive/blob/master/MvcWithUnobtrusive/Scripts/jquery.validate.setup.js#L32-L58) is not being called.

I am expecting to show an error message when the user upload exceeds the set file-size ( in bytes)

I create a repository to show how the `$.validator.addMethod("filesize", function (value, element, param)` is not being called which can be download from https://github.com/CrestApps/MvcWithUnobtrusive

Am I doing something wrong here? How can I register the `filesize` method with `$.validator`?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @CrestApps.
It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@CrestApps, do you have any progress regarding this?

**Comment by CrestApps** [comment]
No. I am still unable to solve this issue and can't find a workaround.

**Comment by mkArtakMSFT** [comment]
Did you get chance to ask this on StackOverflow?

**Comment by CrestApps** [comment]
Not yet. Are you seeing a case of incorrect usage?

**Comment by mkArtakMSFT** [comment]
That's what it looks like from the first look (haven't investigated thoroughly). Hence we recommend people to use StackOverflow first for those type of issues. Then only, if no response, we'll try to spend some time to investigate those issues.

**Comment by CrestApps** [comment]
I added a question on stackoverflow. Is there a specific tag that I should be using?

**Comment by mkArtakMSFT** [comment]
> It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the `asp.net-core-mvc` tag.

**Comment by CrestApps** [comment]
The issue was resolved. jQuery validator by default does not validate hidden inputs. I added `ignore: ":hidden:not('.force-validaion')",` to `$.validator.setDefaults` then I added the `force-validation` class to the hidden input.

**Comment by jerone** [comment]
For anyone interested; below adds the class `val-force` to force validation on hidden element and the class `val-ignore` to ignore some elements:

``` js
	/* Ignore validation on some elements. */
	var ignores = $.validator.defaults.ignore.replace(/(^|\b)(:hidden)($|\b)/gi, ':hidden:not(.val-force)').split(',');
	ignores.push('.val-ignore');
	$.validator.setDefaults({ ignore: ignores.join(',') });
```
